#!/usr/bin/env bash
# Pre-populate commit message with ticket number

branch=$(git current-branch)
ticket_number=$(jira_ticket_number $branch)

if [[ $ticket_number ]]; then
  # If file already contains ticket number before comments, don't do anything
  # Otherwise, prepend the ticket number
  awk "NR == 1 { output = 1 }; /^#/ { output = 0 }; output { print }" $1 |\
    grep -q $ticket_number ||
    printf '%s\n%s\n' "$ticket_number: " "$(cat $1)" > $1
fi
