#!/usr/bin/env bash
# Regenerate ctags

# Ensure ctags Brew is being used. The Apple version is very old
(command -v ctags | grep "/usr/local/" &> /dev/null) || exit

# Do not run if we are in the middle of a rebase
if [[ -d ".git/rebase-merge" ]]; then
  exit
fi


# Only run one ctags process for this directory at the time.
# Otherwise the ctags file is corrupted
echo "$(tput setaf 3)Git Hook:$(tput sgr 0) Creating ctags"

(lockfile .ctags.lock; \
 ctags -R --exclude='*.js' --exclude='*.h' --exclude='*.cpp' &> /dev/null ; \
 rm -f .ctags.lock) &
