#!/usr/bin/env ruby

require "bundler/inline"
require "pry"

gemfile do
  source "https://rubygems.org"
  gem "bitly", "1.1.2"
end

Bitly.use_api_version_3

Bitly.configure do |config|
  config.api_version = 3
  config.access_token = ENV.fetch("BITLY_ACCESS_TOKEN")
end

long_url = ARGV.first || STDIN.first

puts Bitly.client.shorten(long_url).short_url
