#!/usr/bin/env bash
# Finds the last green build in cirlce ci for current project and branch

# Unofficial strict mode:
set -euo pipefail
IFS=$'\n\t'

repo=${1:-$(git remote get-url origin | sed 's/git@github\.com:\(.*\)\.git/\1/')}
branch=${2:-$(git rev-parse --symbolic --abbrev-ref HEAD)}

url="https://circleci.com/api/v1.1/project/github/$repo/tree/$branch?circle-token=$CIRCLE_CLI_TOKEN&limit=5&filter=successful&shallow=true"

curl --silent $url | jq '.[0]["vcs_revision"]' | tr -d '"'
