#!/usr/bin/env ruby

require "bundler/inline"
require "date"

gemfile do
  source "https://rubygems.org"
  gem "activesupport"
end

require "active_support/core_ext/string/inflections"

input = ARGV.empty? ? STDIN.read : ARGV.join(" ")
title = input.titleize.gsub(" ", "")

puts "#{Date.today}-#{title}"
