#!/usr/bin/env ruby

require "net/http"
require "json"
require "yaml"

# Read token /Users/ylans/.config/hub

token = YAML.safe_load(File.read(File.join(Dir.home, ".config", "hub")))["github.com"].first["oauth_token"]
github_url = URI("https://api.github.com/graphql")
owner, repo = `git remote get-url origin`.match(/git@github.com:(.*)\/(.*).git/).captures

query = <<~GRAPHQL
  query {
    repository(owner: \"#{owner}\", name: \"#{repo}\") {
      defaultBranchRef {
        target {
          ... on Commit {
            history(first: 100) {
              nodes {
                oid
                status {
                  state
                }
              }
            }
          }
        }
      }
    }
  }
GRAPHQL

headers = { "Authorization" => "bearer #{token}" }
body = { query: query }.to_json

response = JSON.parse(Net::HTTP.post(github_url, body, headers).body)

last_build = response["data"]["repository"]["defaultBranchRef"]["target"]["history"]["nodes"].find { |node|
  node["status"]["state"] == "SUCCESS"
}

if last_build
  puts last_build["oid"]
else
  exit 1
end
