#!/usr/bin/env bash
# Prints stdin and executes in the given program, commenting the output.
# Example usage:

# $ echo "SELECT NOW()" | io psql
# SELECT NOW()
# --               now
# -- -------------------------------
# --  2019-03-21 16:12:28.371588-07
# -- (1 row)
# --
# -- Time: 0.610 ms

# $ echo "ls -1" | io sh
# ls -1
# # Brewfile
# # LICENSE.txt
# # README.md
# # asdfrc

set -euo pipefail

# Determine which comment pattern to use
case $1 in
  psql)
    comment='-- ' ;;
  uml)
    comment="' " ;;
  node)
    comment="\/\/ ";;
  *)
    comment='# ' ;;
esac

grep -v "^$comment" /dev/stdin | tee >("$@" | sed "s/^/$comment/")
