#!/usr/bin/env bash
# Opens jira on a specific ticket. If no argument or piped stdin is provided, it will try
# to obtain the ticket number from the branch.

# Unofficial strict mode:
set -euo pipefail
IFS=$'\n\t'

base_url="https://procoretech.atlassian.net/browse"

# Check for piped input (open fd 0 - stdin)
if [[ -t 0 ]]
then
  input=${1:-$(git rev-parse --symbolic --abbrev-ref HEAD)}
else
  input=$(cat)
fi

ticket_number=$(jira_ticket_number $input)
if [[ $ticket_number ]]
then
  set -x
  open "$base_url/$ticket_number"
else
  exit 1
fi
