#!/usr/bin/env bash

set -euo pipefail

source_path=~/Personal
sparse_bundle=Secure.sparsebundle
mounted=/Volumes/Secure

# Obtaining Password
read -sp "$sparse_bundle pasword: " PASS

# Mount secure
echo "Mounting $sparse_bundle"
printf "$PASS" | hdiutil attach -stdinpass  $source_path/$sparse_bundle

# Loop until it's unmounted
until [ ! -d $mounted ] ; do
  echo ""
  read -rp "Press enter when ready to unmount $mounted..."
  # Don't error if we can't unmount
  set +eu
  hdiutil detach $mounted
  # Continue exiting on futher errors
  set -eu
done

echo "-------"
echo "Compacting $sparse_bundle"
printf "$PASS" | hdiutil compact -stdinpass  $source_path/$sparse_bundle

echo "-------"
echo "Backing up..."
rclone --progress sync $source_path/$sparse_bundle drive:/$sparse_bundle/

echo "Done"
