#!/usr/bin/env bash

if [ -f ".standard.yml" ]; then
  if [ -f "bin/standardrb" ]; then
    RUBOCOP="bin/standardrb"
  else
    RUBOCOP="standardrb"
  fi
else
  bundle show rubocop &> /dev/null
  if [ $? == 0 ]; then
    RUBOCOP="fast_rubocop"
  else
    RUBOCOP="rubocop"
  fi
fi



$RUBOCOP "$@"
