#!/usr/bin/env bash
set -euo pipefail

if [ -f ".standard.yml" ]; then
  if [ -f "bin/standardrb" ]; then
    RUBOCOP="bin/standardrb"
  else
    RUBOCOP="standardrb"
  fi
else
  if [ "${FAST_RUBOCOP+x}" ]; then
    RUBOCOP="fast_rubocop"
  else
    if [ -f "bin/rubocop" ]; then
      RUBOCOP="bin/rubocop"
    else
      RUBOCOP="rubocop"
    fi
  fi
fi

set -x
$RUBOCOP "$@"
