#!/usr/bin/env bash

# Looking for zeus socket
if [ -S ./.zeus.sock ]; then
  RSPEC="zeus rspec"
else
  # Looking for binstubs
  if [ -f ./bin/rspec ]; then
    RSPEC="bin/rspec"
  else
    if [ -f ./Gemfile ]; then
      RSPEC="bundle exec rspec"
    else
      RSPEC="rspec"
    fi
  fi
fi

if [ $# -eq 0 ]; then
  # No arguments, we will run all specs
  CMD="$RSPEC --format=progress"
else
  CMD="$RSPEC $*"
fi

if [[ "${SMART_RSPEC_QUIET+x}" ]]; then
  echo "$CMD 2> /dev/null"
  $CMD 2> /dev/null
else
  echo "$CMD"
  $CMD
fi
