#!/usr/bin/env bash
# Wraps plantuml to use stdin/stdout and generate unicode diagrams

set -euo pipefail

# Defaults
format="-ttxt"

if [ ${1-default} == '-u' ]; then
  format="-tutxt"
fi

COLUMNS=300 plantuml "$format" -pipe
