#!/usr/bin/env ruby
# Helps wind down after work

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "highline"
  gem "rainbow"
end

require "highline/import"
require "rainbow/refinement"
using Rainbow

AUTO    = "[AUTO]:  ".green
MANUAL  = "[MANUAL]:".cyan

puts "Let's wind down for the day:"
puts "----------------------------"

ask "#{MANUAL} Take note of progress on today's tasks."
ask "#{MANUAL} Reschedule undone tasks. Note resume point"
ask "#{MANUAL} Review calendar for tomorrow"

answer = ask("#{AUTO} Back-up Zettelkasten?") { |q| q.default = "y" }
case answer
when /y/i
  puts "#{AUTO} #{'Zettelkasten'.green} indexing tags"
  system "zk_index_tags"
  puts "#{AUTO} #{'Zettelkasten'.green} backing up"
  system "zk_backup"
else
  puts "#{AUTO} #{'Zettelkasten'.green} Aborting backup"
end

ask "#{MANUAL} It's friday, shutdown your computerv after your done for the day" if Date.today.friday?

puts "----------------------------"
