#!/usr/bin/env bash
# Generate tag index
set -euo pipefail

cd $ZK_HOME

# Generate tag index
rg --no-filename '^\[\[Tags/.*\]\]' |\
  sort --unique |\
  tee Tags.md |\
  xargs -I% -P 4 zk_index_single_tag %
