#!/usr/bin/env bash
# Generate file with links for a specific tag
set -euo pipefail

cd $ZK_HOME
tag=$1
filename=$(echo $tag | zk_link_to_file)

# Index tag usage
echo "# Used in:" > $filename

rg --type md --files-with-matches --fixed-strings "$tag" |\
  grep --invert-match "^Tags.md" |\
  sort |\
  zk_file_to_link >> "$filename"

# Index tag cross-reference
echo "" >> "$filename"
echo "# Tags Cross Refeference:" >> "$filename"

rg --type md --files-with-matches --fixed-strings "$tag" |\
  grep --invert-match "^Tags.md" |\
  xargs rg --no-filename '^\[\[Tags/.*\]\]' |\
  grep --invert-match --fixed-string "$tag" |
  sort |\
  uniq -c |\
  sort -r >> "$filename"
