#!/usr/bin/env bash
# Generate file with links for a specific tag
set -euo pipefail

cd $ZK_HOME

filename=$(echo $1 | zk_link_to_file)

echo "# Used in:" > $filename

rg --type md --files-with-matches --fixed-strings "$1" |\
  grep -v "^Tags.md" |\
  sort |\
  zk_file_to_link >> "$filename"
