#!/usr/bin/env bash
# Interactive search in notes content
set -euo pipefail

cd $ZK_HOME

sk \
  --multi \
  --ansi \
  --interactive \
  --delimiter ':' --nth 1 --cmd 'rg "{}"' \
  --preview 'bat --style=numbers --color=always {1}' \
  | cut -f 1 -d ':'
