#!/usr/bin/env ruby

require "bundler/inline"
require "date"
require "optparse"

gemfile do
  ruby "~> 3.0"
  source "https://rubygems.org"
  gem "activesupport"
end

require "active_support/core_ext/string/inflections"

options = {}
OptionParser.new do |opts|
  opts.on("-s", "--strip", "Don't print a new line after output") do |_v|
    options[:strip] = true
  end
end.parse!

input = ARGV.empty? ? $stdin.read : ARGV.join(" ")
title = input.titleize.gsub(/\W/, "")

printer = options[:strip] ? ->(s) { print s } : ->(s) { puts s }
printer.call "#{Date.today}-#{title}"
