#!/usr/bin/env bash

which ctags | grep "/usr/local/" > /dev/null
if [ $? == 0 ]; then
  pgrep ctags > /dev/null
  if [ $? != 0 ]; then
    echo "Creating ctags..."
    ctags -R --exclude='*.js' > /dev/null 2>&1 &
  fi
fi
